name: nqg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - numpy=1.21.5
  - pip=21.3.1
  - python=3.8.13
  - pytorch=1.11.0
  - pip:
    - allennlp==2.10.0
    - awscli==1.19.84
    - black==21.7b0
    - boto3==1.17.84
    - click<8.1.0
    - deepdiff==5.5.0
    - en-core-web-md @ https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.2.0/en_core_web_md-3.2.0-py3-none-any.whl
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl
    - en-core-web-trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.2.0/en_core_web_trf-3.2.0-py3-none-any.whl
    - flake8==3.9.2
    - fire >= 0.4.0
    - gensim==3.8.3
    - ipython==7.21.0
    - isort==5.9.2
    - jsonnet==0.17.0
    - jupyter==1.0.0
    - jupyterlab==3.0.12
    - jury==2.1.5
    - md2pdf==0.5
    - mypy==0.812
    - neptune-client==0.10.0
    - nltk>=3.3
    - pytest==6.2.5
    - pytorch-ignite==0.4.4
    - sagemaker==2.39.0
    - spacy==3.2.0
    - spacy-alignments==0.8.3
    - spacy-stanza==1.0.0
    - spacy-transformers==1.1.6
    - spacy-wordnet @ git+https://github.com/devrimcavusoglu/spacy-wordnet
    - stanza==1.2.1
    - tensorboard==2.5.0
    - tensorboardx==2.1
    - tokenizers==0.12.1
    - transformers==4.19.4
    - trapper==0.0.9
